### PR TITLE
Issue25 Remove Stackspace from text body reference and screenshots

### PR DESCRIPTION
**Pull request by kellobri**

### CODE REVIEW

**Comment by kellobri** [comment]
@bjkolly -- Some cleanup on aisle stackspace

**Comment by bjkolly** [comment]
Kelly, it looks like there are some comflicing files. I'd fix it, but Im not sure how to. These are the 3 files.
docs/configuring_stackspace_stacks/r-ide.rst
docs/configuring_stackspace_stacks/r-spark.rst
docs/using_stackspace_stacks/B23r/B23r_save-restore.rst

**Comment by kellobri** [comment]
@bjkolly I resolved the conflicts - this should be good to merge now

**Comment by bjkolly** [comment]
Nice!!

**Pull request merged**
